name: Test functionality - GitHubChallengeCLT

on:
  push:
    branches:
      - test
  workflow_dispatch:
  pull request:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'GitHubActionsChallengeFunctionApp' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.301' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'GitHubChallengeCLT'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F5B05A45FC5F4152BE391535F9F33096 }}
